import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { LandmarkService, area, query, normalize, TTL } = require('./service');
const input={id:'demo',name:'Public demo',bounds:{south:52.469,west:4.800,north:52.480,east:4.827}};
const raw={elements:[{type:'node',id:1,lat:52.475,lon:4.82,tags:{man_made:'windmill',name:'Mill'}},{type:'way',id:2,tags:{leisure:'playground'},geometry:[{lat:52.472,lon:4.81},{lat:52.473,lon:4.81},{lat:52.473,lon:4.812},{lat:52.472,lon:4.81}]},{type:'way',id:3,tags:{waterway:'river',width:'12'},geometry:[{lat:52.47,lon:4.8},{lat:52.475,lon:4.815},{lat:52.48,lon:4.82}]}]};
async function fixture(t, opts={}) {const dir=await fs.mkdtemp(path.join(os.tmpdir(),'fonsters-landmarks-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return new LandmarkService({directory:dir,...opts});}
test('validates finite bounded geographic areas without accepting arbitrary queries',()=>{assert.throws(()=>area({...input,id:'../escape'}));assert.throws(()=>area({...input,bounds:{south:0,west:0,north:1,east:1}}));assert.throws(()=>area({...input,bounds:{...input.bounds,west:NaN}}));assert.match(query(area(input)),/out geom/);});
test('preserves actual points, polygon rings, waterway vertices and attribution',()=>{const s=normalize(raw,area(input),0);assert.equal(s.features.length,3);assert.equal(s.features[0].geometry.type,'Point');assert.equal(s.features[1].geometry.type,'Polygon');assert.deepEqual(s.features[2].geometry.coordinates,[[4.8,52.47],[4.815,52.475],[4.82,52.48]]);assert.equal(s.features[2].widthMeters,12);assert.equal(s.coverage.exhaustive,false);assert.equal(s.coverage.surveyedAbsence,false);assert.equal(s.source.license,'ODbL-1.0');});
test('never bridges missing geometry; rejects upstream runtime remarks',()=>{const broken=structuredClone(raw);broken.elements[2].geometry[1]={};assert.equal(normalize(broken,area(input),0).features.length,2);assert.throws(()=>normalize({...raw,remark:'timeout'},area(input),0));assert.equal(normalize({elements:[]},area(input),0).coverage.surveyedAbsence,false);});
test('imports once, coalesces concurrent reads, survives restart, and serves stale offline',async t=>{let calls=0,now=1000000;const s=await fixture(t,{enabled:true,now:()=>now,fetchImpl:async()=>{calls++;return new Response(JSON.stringify(raw));}});const results=await Promise.all([s.snapshot(input),s.snapshot(input),s.snapshot(input)]);assert.equal(calls,1);assert.equal(results[2].delivery.source,'cache');const restarted=new LandmarkService({directory:s.directory,now:()=>now});assert.equal((await restarted.snapshot(input)).features.length,3);now+=TTL+1;const stale=await restarted.snapshot(input);assert.equal(stale.delivery.stale,true);assert.equal(stale.features.length,3);});
test('disabled imports transmit nothing and distinguish unknown from empty mapping',async t=>{let calls=0;const s=await fixture(t,{fetchImpl:()=>{calls++;throw new Error('should not fetch');}});const result=await s.snapshot(input);assert.equal(calls,0);assert.equal(result.coverage.status,'unknown');assert.equal(result.fetchedAt,null);});
test('budgets reserve failed requests and return stale snapshots on upstream outage',async t=>{let calls=0,good=true,now=0;const s=await fixture(t,{enabled:true,dailyRequests:2,now:()=>now,fetchImpl:async()=>{calls++;if(!good)throw new Error('offline');return new Response(JSON.stringify(raw));}});await s.snapshot(input);good=false;now+=TTL+1;assert.equal((await s.snapshot(input)).delivery.reason,'offline');assert.equal((await s.snapshot(input)).delivery.reason,'offline');assert.equal((await s.snapshot(input)).delivery.reason,'import_budget_exhausted');assert.equal(calls,3);});
test('caps response size and rejects accidental non-durable deployments',async t=>{assert.throws(()=>new LandmarkService());const s=await fixture(t,{enabled:true,dailyBytes:4096,fetchImpl:async()=>new Response(' '.repeat(5000))});assert.equal((await s.snapshot(input)).delivery.reason,'source_too_large');});
test('shared-directory upstream lock fails closed and preserves another importer lock',async t=>{const s=await fixture(t,{enabled:true,fetchImpl:()=>{throw new Error('must not fetch');}});await fs.mkdir(path.join(s.directory,'import.lock'));assert.equal((await s.snapshot(input)).delivery.reason,'import_busy');await fs.stat(path.join(s.directory,'import.lock'));});
test('read-only catalog has no upstream imports, accepts named areas only and defaults closed',()=>{const {handle}=require('./catalog');assert.equal(handle({method:'POST'}).status,503);assert.equal(handle({method:'POST',enabled:true,body:{latitude:52}}).status,400);assert.equal(handle({method:'POST',enabled:true,query:'?area=private'}).status,400);assert.equal(handle({method:'GET',enabled:true}).status,405);const features=JSON.parse(handle({method:'POST',enabled:true,body:{areaId:'zaanse-schans'}}).body).features;for(const kind of ['windmill','playground','waterway'])assert.ok(features.some(f=>f.kind===kind));});

test("width with unsupported units is omitted rather than mislabeled meters",()=>{const value=structuredClone(raw);value.elements[2].tags.width="12 ft";assert.equal(normalize(value,area(input),0).features.at(-1).widthMeters,undefined);});
